"""store the outreach draft per posting and upload

Revision ID: 0fa7461ba37a
Revises: 2b6e7e935d9e
Create Date: 2026-08-23 18:45:06.527267

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0fa7461ba37a"
down_revision: str | None = "2b6e7e935d9e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "outreach_drafts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("student_id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column("resume_master_id", sa.Integer(), nullable=True),
        sa.Column("subject", sa.String(length=300), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("written", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["resume_master_id"], ["resume_masters.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["student_id"], ["students.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "student_id", "job_id", "resume_master_id", name="uq_outreach_student_job_resume"
        ),
    )
    op.create_index(
        op.f("ix_outreach_drafts_job_id"), "outreach_drafts", ["job_id"], unique=False
    )
    op.create_index(
        op.f("ix_outreach_drafts_resume_master_id"),
        "outreach_drafts",
        ["resume_master_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_outreach_drafts_student_id"), "outreach_drafts", ["student_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_outreach_drafts_student_id"), table_name="outreach_drafts")
    op.drop_index(op.f("ix_outreach_drafts_resume_master_id"), table_name="outreach_drafts")
    op.drop_index(op.f("ix_outreach_drafts_job_id"), table_name="outreach_drafts")
    op.drop_table("outreach_drafts")
    # ### end Alembic commands ###
