"""record which rewrites the student approved

Revision ID: 2b6e7e935d9e
Revises: c4a1b2d3e5f6
Create Date: 2026-08-23 16:49:46.388404

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "2b6e7e935d9e"
down_revision: str | None = "c4a1b2d3e5f6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tailored_resumes",
        sa.Column(
            "approved_bullet_ids",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tailored_resumes", "approved_bullet_ids")
    # ### end Alembic commands ###
