"""create the tables the empty migrations missed

Revision ID: 31dfd5f52bf0
Revises: 8445d7dd0adf
Create Date: 2026-08-23 14:50:46.808085

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "31dfd5f52bf0"
down_revision: str | None = "8445d7dd0adf"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "match_scores",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("student_id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column("resume_master_id", sa.Integer(), nullable=False),
        sa.Column("total", sa.Integer(), nullable=False),
        sa.Column("skill_points", sa.Integer(), nullable=False),
        sa.Column("experience_points", sa.Integer(), nullable=False),
        sa.Column("keyword_points", sa.Integer(), nullable=False),
        sa.Column("freshness_points", sa.Integer(), nullable=False),
        sa.Column("skill_state", sa.String(length=16), nullable=False),
        sa.Column("experience_state", sa.String(length=16), nullable=False),
        sa.Column("keyword_state", sa.String(length=16), nullable=False),
        sa.Column("freshness_state", sa.String(length=16), nullable=False),
        sa.Column("matched_skills", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("missing_skills", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("required_years", sa.Float(), nullable=True),
        sa.Column("requirement_basis", sa.String(length=16), nullable=True),
        sa.Column("requirement_phrase", sa.String(length=200), nullable=True),
        sa.Column(
            "computed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["resume_master_id"], ["resume_masters.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["student_id"], ["students.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "student_id", "job_id", "resume_master_id", name="uq_match_score_student_job_resume"
        ),
    )
    op.create_index(
        "ix_match_score_student_total", "match_scores", ["student_id", "total"], unique=False
    )
    op.create_index(op.f("ix_match_scores_job_id"), "match_scores", ["job_id"], unique=False)
    op.create_index(
        op.f("ix_match_scores_resume_master_id"),
        "match_scores",
        ["resume_master_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_match_scores_student_id"), "match_scores", ["student_id"], unique=False
    )
    op.create_table(
        "tailored_resumes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("student_id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column("resume_master_id", sa.Integer(), nullable=False),
        sa.Column("bullets", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("gaps", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("changed_count", sa.Integer(), nullable=False),
        sa.Column("rejected_count", sa.Integer(), nullable=False),
        sa.Column("basis", sa.String(length=16), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["resume_master_id"], ["resume_masters.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["student_id"], ["students.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "student_id", "job_id", "resume_master_id", name="uq_tailored_student_job_resume"
        ),
    )
    op.create_index(
        op.f("ix_tailored_resumes_job_id"), "tailored_resumes", ["job_id"], unique=False
    )
    op.create_index(
        op.f("ix_tailored_resumes_resume_master_id"),
        "tailored_resumes",
        ["resume_master_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tailored_resumes_student_id"), "tailored_resumes", ["student_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tailored_resumes_student_id"), table_name="tailored_resumes")
    op.drop_index(op.f("ix_tailored_resumes_resume_master_id"), table_name="tailored_resumes")
    op.drop_index(op.f("ix_tailored_resumes_job_id"), table_name="tailored_resumes")
    op.drop_table("tailored_resumes")
    op.drop_index(op.f("ix_match_scores_student_id"), table_name="match_scores")
    op.drop_index(op.f("ix_match_scores_resume_master_id"), table_name="match_scores")
    op.drop_index(op.f("ix_match_scores_job_id"), table_name="match_scores")
    op.drop_index("ix_match_score_student_total", table_name="match_scores")
    op.drop_table("match_scores")
    # ### end Alembic commands ###
