"""cache the parsed experience requirement

Revision ID: 8445d7dd0adf
Revises: b7f9dad87b7e
Create Date: 2026-08-23 14:39:10.730660

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '8445d7dd0adf'
down_revision: str | None = 'b7f9dad87b7e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('required_years', sa.Float(), nullable=True))
    op.add_column('jobs', sa.Column('requirement_basis', sa.String(length=16), nullable=True))
    op.add_column('jobs', sa.Column('requirement_phrase', sa.String(length=200), nullable=True))
    op.add_column('jobs', sa.Column('experience_parsed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'experience_parsed_at')
    op.drop_column('jobs', 'requirement_phrase')
    op.drop_column('jobs', 'requirement_basis')
    op.drop_column('jobs', 'required_years')
    # ### end Alembic commands ###
