"""tailored resumes

Revision ID: b7f9dad87b7e
Revises: bf60a36044e2
Create Date: 2026-08-23 14:33:48.654452

"""

from collections.abc import Sequence

revision: str = 'b7f9dad87b7e'
down_revision: str | None = 'bf60a36044e2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
