"""match scores for the scored feed

Revision ID: bf60a36044e2
Revises: a4cdc59cdd17
Create Date: 2026-08-20 21:09:48.214385

"""

from collections.abc import Sequence

revision: str = 'bf60a36044e2'
down_revision: str | None = 'a4cdc59cdd17'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
