"""The demo resume, as a product asset.

Served by the `DEMO_MODE` parser and used to build the seeded demo account, so it lives
with the adapters rather than under tests — app code must not import from the test
package.

Generated by `scripts/make_sample_resume_pdf.py`. The person is fictional: this
repository is public, and a real resume in it would put a name, phone number and email
address on a permanent public URL.
"""

from pathlib import Path

DEMO_RESUME_PATH = Path(__file__).parent / "demo_resume.pdf"
DEMO_RESUME_FILENAME = "alex-rivera-resume.pdf"


def demo_resume_bytes() -> bytes:
    return DEMO_RESUME_PATH.read_bytes()
